-- Baseline schema. Portable across H2 and PostgreSQL.
--
-- Idempotent on purpose: databases created before migrations existed (by Hibernate's
-- ddl-auto=update) are baselined at version 0, so this script also runs against them.
-- It creates what's missing, adds columns introduced over time, and converts the
-- native ENUM columns H2 generated into VARCHAR so new enum values never need a
-- manual ALTER again.

CREATE TABLE IF NOT EXISTS agents (
    id                  VARCHAR(255) NOT NULL PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    status              VARCHAR(30)  NOT NULL,
    active_order_count  INTEGER      NOT NULL,
    current_zone        VARCHAR(255),
    max_capacity        INTEGER
);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS last_heartbeat_at TIMESTAMP;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS status_note VARCHAR(200);
ALTER TABLE agents ALTER COLUMN status SET DATA TYPE VARCHAR(30);

CREATE TABLE IF NOT EXISTS orders (
    id                 VARCHAR(255) NOT NULL PRIMARY KEY,
    description        VARCHAR(500) NOT NULL,
    assigned_agent_id  VARCHAR(255) NOT NULL,
    status             VARCHAR(30)  NOT NULL,
    created_at         TIMESTAMP    NOT NULL,
    pickup_zone        VARCHAR(255),
    dropoff_zone       VARCHAR(255),
    sla_deadline       TIMESTAMP
);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS recommended_agent_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS followed_recommendation BOOLEAN;
ALTER TABLE orders ALTER COLUMN status SET DATA TYPE VARCHAR(30);

CREATE TABLE IF NOT EXISTS reassignment_suggestions (
    id                    VARCHAR(255)     NOT NULL PRIMARY KEY,
    order_id              VARCHAR(255)     NOT NULL,
    recommended_agent_id  VARCHAR(255)     NOT NULL,
    confidence            DOUBLE PRECISION NOT NULL,
    reasoning             VARCHAR(2000)    NOT NULL,
    status                VARCHAR(30)      NOT NULL,
    trigger_reason        VARCHAR(30)      NOT NULL,
    source                VARCHAR(255),
    created_at            TIMESTAMP        NOT NULL,
    decided_at            TIMESTAMP
);
ALTER TABLE reassignment_suggestions ADD COLUMN IF NOT EXISTS source VARCHAR(255);
ALTER TABLE reassignment_suggestions ADD COLUMN IF NOT EXISTS routing_millis BIGINT;
ALTER TABLE reassignment_suggestions ALTER COLUMN status SET DATA TYPE VARCHAR(30);
ALTER TABLE reassignment_suggestions ALTER COLUMN trigger_reason SET DATA TYPE VARCHAR(30);
CREATE INDEX IF NOT EXISTS idx_suggestion_order ON reassignment_suggestions (order_id);
CREATE INDEX IF NOT EXISTS idx_suggestion_status ON reassignment_suggestions (status);

CREATE TABLE IF NOT EXISTS activity_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at             TIMESTAMP    NOT NULL,
    type           VARCHAR(40)  NOT NULL,
    actor          VARCHAR(10)  NOT NULL,
    order_id       VARCHAR(255),
    agent_id       VARCHAR(255),
    suggestion_id  VARCHAR(255),
    message        VARCHAR(500) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_activity_at ON activity_log (at);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key    VARCHAR(100) NOT NULL PRIMARY KEY,
    setting_value  VARCHAR(500) NOT NULL,
    updated_at     TIMESTAMP    NOT NULL
);
